channels:
    - conda-forge
    - defaults
dependencies:
    # data science starts here
    - matplotlib
    - numpy
    - pandas
    - scikit-learn
    - scipy
    # such a nag
    - pip
    - pip:
        - pyforest
