channels:
    - conda-forge
    - defaults
dependencies:
    # project candidate packaging
    - ftfy
    - jellyfish
    - numexpr
    - pyreadstat
    - python-levenshtein
    - sparse_dot_topn
    - textdistance
    # such a nag
    - pip
    - pip:
        - recordlinkage
        - strsimpy
        - string-grouper
