channels:
    - conda-forge
    - defaults
dependencies:
    # set the version up the top
    - python
    # package managers
    - conda
    - pip
    # tools
    - black=19.10b
    - flake8-bugbear
    - ipython
    - isort
    - mypy
    - pre-commit
    - pylint
    - pytest
    - pytest-cov
    - requests
